# Generated by Django 4.2 on 2025-01-11 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_trainer_alter_pokemon_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('F', 'Fuego'), ('E', 'Elctrico'), ('T', 'Tierra'), ('A', 'Agua'), ('L', 'Lgartija'), ('P', 'Planta')], max_length=30),
        ),
    ]
